##############################################
####	Makefile for DataScope for 68881 code
###############################################
LDIR	=	:DSLibs:
#
LIBS	=	{LDIR}tcplibd1.o		¶
			{LDIR}tcplibd2.o		¶
			{LDIR}txtlib1.o		¶
			{LDIR}txtlib2.o		¶
			{LDIR}cmplib.o		¶
			{LDIR}df.a
#
OBJS	=	{LDIR}fparse.y.c.o	¶
			{LDIR}fview.c.o		¶
			{LDIR}f2view.c.o
#
LOPT	=	-d			¶
			-t	APPL	¶
			-c 'NCSf'	¶
			-sym on
#

Syslibs881	= "{CLibraries}"CLib881.o		¶
			"{Libraries}"Interface.o	¶
			"{CLibraries}"StdCLib.o 	¶
			"{CLibraries}"CSANELib881.o ¶
 			"{CLibraries}"Math881.o		¶
			"{Libraries}Runtime.o"		¶
			
###################################
all			Ä	DataScope ¶
				{LDIR}DataScope.r	¶
				{LIBS}				¶
				{OBJS}
#
DataScope 	ÄÄ	{LDIR}DataScope.r
	Rez		Types.r					¶
			SysTypes.r				¶
			{LDIR}DataScope.r		¶
			-o DataScope
#
DataScope	ÄÄ	{OBJS}	{LIBS} {LDIR}DataScope.r
	Link	{LOPT} {OBJS} {LIBS} {Syslibs881} -o DataScope
