.\" Man page for xdizzy, by Juri Munkki
.TH xdizzy 1.0 "Dec 29 1990"
.SH NAME
\fIxdizzy\fR \- A Digital Simulator for X/Motif
.SH SYNOPSIS
.B xdizzy

.SH DESCRIPTION
.I xdizzy
is a digital circuit simulator, on top of the
X11 window system using Motif.

.SH USING XDIZZY
You should read DizzyDoc to learn how to use xdizzy.


.SH NOTES

Xdizzy doesn't use resources yet. You can change the file selection dialog, but that's about it. Changes to this are welcome.


.SH COPYRIGHT

This is copyright 1990 Juri Munkki. Read DizzyDoc for a more complete copyright and information on who is allowed to use this program and how.

