#define	MAX_BULLETS			100
#define	MAX_LASER_BEAMS		20
#define	MAX_BOMBS			20
#define	MAX_LARGE_BOMBS		10
#define	MAX_EXPLOSIONS		30
#define	MAX_SHELLS			20
#define	MAX_TRACERS			20
#define	MAX_MISSILES		10
#define	MAX_CIRCLES			10
#define	MAX_BLASTERS		30

#define	BULLET_SPEED		10L
#define	BLASTER_SPEED		10
#define	TRACER_SPEED		10
#define	SHELL_SPEED			3
#define	SMART_BOMB_SPEED	8L
#define	CIRCLE_RADIUS_GROWTH 4L
#define	BULLET_FUSE_LENGTH	50
#define	SHELL_BULLET_FUSE	10
#define	BOMB_FUSE_LENGTH	20
#define	MISSILE_FUSE_LENGTH	2000
#define TRACER_FUSE_LENGTH	100
#define CIRCLE_FUSE_LENGTH	30
#define BLASTER_FUSE_LENGTH	25
#define SHELL_INTERVAL		60
#define MISSILE_INTERVAL	200
#define	MISSILE_ACCEL		(0x1C000 >> 8)

#define INITIAL_BLASTER_LENGTH	4

#define	LASER_LENGTH		400

#define BULLET_DAMAGE		5
#define TRACER_DAMAGE		40
#define BOMB_DAMAGE			20
#define LINE_DAMAGE			20
#define LARGE_BOMB_DAMAGE	50
#define CIRCLE_DAMAGE		30