#####################################
#	Make File for DataScope DSResources
#####################################
LDIR	= ::DSLibs:
#####################################
{LDIR}DataScope.r	Ä	DataScope.rsrc
	DeRez	DataScope.rsrc		¶
			Types.r				¶
			SysTypes.r			¶
			> {LDIR}DataScope.r
#	
