.TH CCONQ 6 GNU
.SH NAME
cconq - curses-based configurable strategy game
.SH SYNOPSIS
.B
cconq
[ options ] ...
.SH DESCRIPTION
\fIcconq\fP is a configurable multi-player strategy game.

The following options apply to both \fIcconq\fP and \fIxconq\fP:

.so ../kernel/cmdline.6in

Unlike \fIxconq(6)\fP, \fIcconq\fP allows only one human player in a game.

.so ../kernel/misc.6in

.so ../kernel/diagnost.6in

.so ../kernel/bugs.6in
