#! /bin/sh

# Update the dependencies of the Makefile in place.
# usage: $0 $(CFLAGS) $(SRCS)

{
	sed '/^# DO NOT DELETE THIS LINE/,$d' Makefile &&
	echo &&
	echo '# DO NOT DELETE THIS LINE -- make depend depends on it.' &&
	echo &&
	cc -M $*
} >>Mf.dep &&
mv Makefile Makefile.bak &&
mv Mf.dep Makefile
