/*
 * DO NOT EDIT -- generated by the Makefile
 */
 
/* the default :-separated search path */
#ifndef DEFAULTCALCPATH
#define DEFAULTCALCPATH ":yang:applications:calc:lib"
#endif /* DEFAULTCALCPATH */

/* the default :-separated startup file list */
#ifndef DEFAULTCALCRC
#define DEFAULTCALCRC ":yang:applications:calc:lib"
#endif /* DEFAULTCALCRC */

/* the location of the help directory */
#ifndef HELPDIR
#define HELPDIR ":yang:applications:calc:help"
#endif /* HELPDIR */

/* the default pager to use */
#ifndef DEFAULTCALCPAGER
#define DEFAULTCALCPAGER " "
#endif /* DEFAULTCALCPAGER */
