void	main(void);
void	ToolBoxInit(void);
void	DialogInit(void);
void	WindowInit(void);
void	MenuBarInit(void);
void	MainLoop(void);
void	HandleMouseDown(EventRecord *theEvent);
void	HandleMenuChoice(long menuChoice);
void	HandleAppleChoice(short theItem);
void	HandleFileChoice(short theItem);
void	DoCellularAutomata(void);
void	CalcResults(void);
void	GraphResults(void);
void	DisplayCellWindow(void);
long	Randomize(long range);
void	PlaceRandomCells(void);
void	HandleEvent(EventRecord *theEvent);
