
/* menuseg.c */
void CloseCaptureFile(short w);
void AdjustMenus(void);
void switchMenus(short which);
void setupmenu(short def);
void CheckOpSpecSubmenu(void);
void SetupOpSpecSubmenu(MenuHandle theMenu);
void updateMenuChecks(void);
void DisplayMacBinary(void);
void CheckFonts(void);
void applAbout(void);
short ReallyClose(short scrn);
PicHandle RGtoPICT(short i);
void copyGraph(short dnum);
void copyText(short vs);
void copyTable(short vs);
void paste(void);
void displayStatus(short n);
void changeport(short oldprt, short newprt);
Boolean	HandleQuit(void);
void HandleMenuCommand(long mResult, short modifiers);
void	CheckNational(short choice);
short portsOpen(void);
void extractmenu(short screen);
void addinmenu(short screen, Str255 temps, char mark);
void SetMenuMarkToOpeningForAGivenScreen(short scrn);
void SetMenuMarkToLiveForAGivenScreen(short scrn);
void DoTheMenuChecks(void);
void SetMenusForSelection(short selected);
void SetScreenDimensions(short scrn);
void	ChangeWindowName(WindowPtr	theWindow);
void	set_new_window_name(Str255 theName, WindowPtr theWindow);
